version: "3"
services:
  flask:
    build: ./app
    ports:
      - "5000:5000"
    volumes:
      - "./app:/test_app"
      - "./test:/test_app/test"  
    networks:
      - mynetwork

networks:
  mynetwork:
